LOCAL_HOST = "127.0.0.1"
SERVER_HOST = "218.235.38.85"

BACKEND_HOST = SERVER_HOST
BACKEND_URL = f"http://{BACKEND_HOST}:8000/api"

GET_CGM = f"{BACKEND_URL}/cgm"
GET_EXERCISE = f"{BACKEND_URL}/exercise"
GET_MEAL = f"{BACKEND_URL}/meal"
GET_MEDICINE = f"{BACKEND_URL}/medicine"
GET_MEAL_FOOD = f"{BACKEND_URL}/meal_food"